import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
import '@/style/globals.css'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`min-h-full antialiased`}>
        <div className="relative flex h-screen min-h-full w-full flex-col items-center justify-center">
          <main className=' w-full flex-gro p-2'>{children}</main>
        </div>
      </body>
    </html>
  )
}
